// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3o651QVhcpsLkCghzXhPHOtVihmHIV_0',
    appId: '1:360127361261:web:51a1ee876af4c6a096dce4',
    messagingSenderId: '360127361261',
    projectId: 'sipaling-undip',
    authDomain: 'sipaling-undip.firebaseapp.com',
    storageBucket: 'sipaling-undip.appspot.com',
    measurementId: 'G-SSFRJTR396',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbbRSikEc5y60Ik2hyS6hkRyOUlYyDEbo',
    appId: '1:360127361261:android:fb776b546d95804a96dce4',
    messagingSenderId: '360127361261',
    projectId: 'sipaling-undip',
    storageBucket: 'sipaling-undip.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpsYgJYnx0kNnt2CjUyqQyn4DEdDt4lyo',
    appId: '1:360127361261:ios:e9f9e9ab5dccbaf896dce4',
    messagingSenderId: '360127361261',
    projectId: 'sipaling-undip',
    storageBucket: 'sipaling-undip.appspot.com',
    iosBundleId: 'com.example.siPalingUndip',
  );
}
